(define pi 3.14159)
(define radius 10)
(define circumference (* 2 pi radius))

(define (square x) (* x x))
(define (sum-of-squares x y)
  (+ (square x) (square y)))
(define (f a)
  (sum-of-squares (+ a 1) (* a 2)))

(define (_abs x)
  (cond ((> x 0) x)
        ((= x 0) 0)
        ((< x 0) (- x))))
(define (_abs2 x)
  (cond ((< x 0) (- x))
        (else x)))
(define (_abs3 x)
  (if (< x 0)
      (- x)
      x))

(* pi (* radius radius))
circumference
(square 4)
(square (square 3))
(f 5)
(_abs 10)
(_abs2 10)
(_abs3 10)